// Sistema de alertas y notificaciones para cumplimiento NOM-035
import { useQuery } from "@tanstack/react-query";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";

interface ComplianceAlert {
  id: string;
  type: 'critical' | 'warning' | 'info';
  title: string;
  description: string;
  action: string;
  deadline?: string;
  relatedEmployee?: string;
  autoGenerated: boolean;
  createdAt: Date;
}

export default function ComplianceAlerts() {
  const { data: employees = [] } = useQuery({ queryKey: ['/api/employees'] });
  const { data: evaluations = [] } = useQuery({ queryKey: ['/api/evaluations'] });
  const { data: notifications = [] } = useQuery({ queryKey: ['/api/email-notifications'] });

  // Generar alertas automáticas basadas en el estado actual
  const generateAlerts = (): ComplianceAlert[] => {
    const alerts: ComplianceAlert[] = [];
    const now = new Date();

    // Empleados sin evaluación
    const unevaluatedEmployees = employees.filter((emp: any) => 
      !evaluations.some((evaluation: any) => evaluation.employeeId === emp.id)
    );
    
    if (unevaluatedEmployees.length > 0) {
      alerts.push({
        id: 'unevaluated-employees',
        type: 'warning',
        title: 'Empleados sin evaluación',
        description: `${unevaluatedEmployees.length} empleado(s) no han completado su evaluación de riesgos psicosociales`,
        action: 'Programar evaluaciones pendientes',
        autoGenerated: true,
        createdAt: now
      });
    }

    // Empleados sin evaluación de eventos traumáticos
    const withoutTraumaticEval = employees.filter((emp: any) => 
      !evaluations.some((evaluation: any) => 
        evaluation.employeeId === emp.id && evaluation.questionnaireType === "traumatic_events"
      )
    );

    if (withoutTraumaticEval.length > 0) {
      alerts.push({
        id: 'missing-traumatic-eval',
        type: 'critical',
        title: 'Evaluaciones traumáticas pendientes',
        description: `${withoutTraumaticEval.length} empleado(s) requieren evaluación de acontecimientos traumáticos severos (Obligatorio NOM-035)`,
        action: 'Aplicar cuestionario de eventos traumáticos',
        deadline: 'Inmediato',
        autoGenerated: true,
        createdAt: now
      });
    }

    // Empleados con exposición traumática
    const exposedEmployees = evaluations.filter((evaluation: any) => evaluation.hasTraumaticExposure);
    exposedEmployees.forEach((evaluation: any) => {
      const employee = employees.find((emp: any) => emp.id === evaluation.employeeId);
      alerts.push({
        id: `traumatic-exposure-${evaluation.id}`,
        type: 'critical',
        title: 'Exposición traumática detectada',
        description: 'Trabajador requiere canalización inmediata a servicios médicos y psicológicos especializados',
        action: 'Contactar servicios médicos',
        relatedEmployee: employee ? `${employee.nombre} ${employee.apellidos}` : 'Empleado desconocido',
        deadline: 'Inmediato',
        autoGenerated: true,
        createdAt: new Date(evaluation.completedAt)
      });
    });

    // Empleados de alto riesgo
    const highRiskEmployees = evaluations.filter((evaluation: any) => 
      ['alto', 'muy-alto'].includes(evaluation.riskLevel)
    );
    
    highRiskEmployees.forEach((evaluation: any) => {
      const employee = employees.find((emp: any) => emp.id === evaluation.employeeId);
      alerts.push({
        id: `high-risk-${evaluation.id}`,
        type: 'warning',
        title: 'Empleado en riesgo alto',
        description: 'Requiere plan de intervención y seguimiento especializado',
        action: 'Crear plan de intervención',
        relatedEmployee: employee ? `${employee.nombre} ${employee.apellidos}` : 'Empleado desconocido',
        deadline: '15 días hábiles',
        autoGenerated: true,
        createdAt: new Date(evaluation.completedAt)
      });
    });

    // Notificaciones pendientes
    const pendingNotifications = notifications.filter((notif: any) => notif.status === 'pending');
    if (pendingNotifications.length > 0) {
      alerts.push({
        id: 'pending-notifications',
        type: 'info',
        title: 'Notificaciones pendientes',
        description: `${pendingNotifications.length} notificación(es) por enviar`,
        action: 'Revisar y procesar notificaciones',
        autoGenerated: true,
        createdAt: now
      });
    }

    // Evaluaciones próximas a vencer (si tuviéramos fechas de vencimiento)
    const oldEvaluations = evaluations.filter((evaluation: any) => {
      const evalDate = new Date(evaluation.completedAt);
      const daysSince = Math.floor((now.getTime() - evalDate.getTime()) / (1000 * 60 * 60 * 24));
      return daysSince > 365; // Más de un año
    });

    if (oldEvaluations.length > 0) {
      alerts.push({
        id: 'outdated-evaluations',
        type: 'info',
        title: 'Evaluaciones para renovar',
        description: `${oldEvaluations.length} evaluación(es) tienen más de un año de antigüedad`,
        action: 'Programar re-evaluaciones',
        deadline: '30 días',
        autoGenerated: true,
        createdAt: now
      });
    }

    return alerts.sort((a, b) => {
      // Ordenar por prioridad: critical > warning > info
      const priority = { critical: 3, warning: 2, info: 1 };
      return priority[b.type] - priority[a.type];
    });
  };

  const alerts = generateAlerts();
  const criticalAlerts = alerts.filter(a => a.type === 'critical');
  const warningAlerts = alerts.filter(a => a.type === 'warning');
  const infoAlerts = alerts.filter(a => a.type === 'info');

  const getAlertColor = (type: string) => {
    switch (type) {
      case 'critical': return 'border-red-200 bg-red-50';
      case 'warning': return 'border-yellow-200 bg-yellow-50';
      case 'info': return 'border-blue-200 bg-blue-50';
      default: return 'border-gray-200 bg-gray-50';
    }
  };

  const getAlertBadgeColor = (type: string) => {
    switch (type) {
      case 'critical': return 'bg-red-100 text-red-800';
      case 'warning': return 'bg-yellow-100 text-yellow-800';
      case 'info': return 'bg-blue-100 text-blue-800';
      default: return 'bg-gray-100 text-gray-800';
    }
  };

  const getAlertIcon = (type: string) => {
    switch (type) {
      case 'critical': return 'fas fa-exclamation-triangle';
      case 'warning': return 'fas fa-exclamation-circle';
      case 'info': return 'fas fa-info-circle';
      default: return 'fas fa-bell';
    }
  };

  return (
    <div className="space-y-6">
      {/* Resumen de alertas */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
        <Card>
          <CardContent className="p-4 text-center">
            <div className="text-2xl font-bold text-slate-900">{alerts.length}</div>
            <div className="text-sm text-slate-600">Total Alertas</div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="p-4 text-center">
            <div className="text-2xl font-bold text-red-600">{criticalAlerts.length}</div>
            <div className="text-sm text-slate-600">Críticas</div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="p-4 text-center">
            <div className="text-2xl font-bold text-yellow-600">{warningAlerts.length}</div>
            <div className="text-sm text-slate-600">Advertencias</div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="p-4 text-center">
            <div className="text-2xl font-bold text-blue-600">{infoAlerts.length}</div>
            <div className="text-sm text-slate-600">Informativas</div>
          </CardContent>
        </Card>
      </div>

      {/* Alertas críticas destacadas */}
      {criticalAlerts.length > 0 && (
        <Alert className="border-red-200 bg-red-50">
          <AlertTitle className="text-red-800">
            <i className="fas fa-exclamation-triangle mr-2"></i>
            Acción Inmediata Requerida
          </AlertTitle>
          <AlertDescription className="text-red-700">
            {criticalAlerts.length} alerta(s) crítica(s) requieren atención inmediata para mantener el cumplimiento de la NOM-035-STPS-2018.
          </AlertDescription>
        </Alert>
      )}

      {/* Lista de alertas */}
      <div className="space-y-4">
        {alerts.map((alert) => (
          <Card key={alert.id} className={`border ${getAlertColor(alert.type)}`}>
            <CardHeader className="pb-3">
              <div className="flex items-start justify-between">
                <div className="flex items-start gap-3">
                  <i className={`${getAlertIcon(alert.type)} text-lg mt-1 ${
                    alert.type === 'critical' ? 'text-red-600' :
                    alert.type === 'warning' ? 'text-yellow-600' :
                    'text-blue-600'
                  }`}></i>
                  <div className="flex-1">
                    <CardTitle className="text-sm font-semibold">{alert.title}</CardTitle>
                    <p className="text-sm text-slate-600 mt-1">{alert.description}</p>
                    {alert.relatedEmployee && (
                      <p className="text-xs text-slate-500 mt-1">
                        <strong>Empleado:</strong> {alert.relatedEmployee}
                      </p>
                    )}
                  </div>
                </div>
                <div className="flex items-center gap-2">
                  {alert.deadline && (
                    <Badge variant="outline" className="text-xs">
                      {alert.deadline}
                    </Badge>
                  )}
                  <Badge className={getAlertBadgeColor(alert.type)}>
                    {alert.type === 'critical' ? 'Crítico' :
                     alert.type === 'warning' ? 'Advertencia' : 'Info'}
                  </Badge>
                </div>
              </div>
            </CardHeader>
            <CardContent className="pt-0">
              <div className="flex items-center justify-between">
                <div className="text-xs text-slate-500">
                  {alert.autoGenerated ? 'Generada automáticamente' : 'Manual'} • 
                  {alert.createdAt.toLocaleDateString('es-MX')} {alert.createdAt.toLocaleTimeString('es-MX')}
                </div>
                <Button size="sm" variant={alert.type === 'critical' ? 'default' : 'outline'}>
                  {alert.action}
                </Button>
              </div>
            </CardContent>
          </Card>
        ))}
      </div>

      {alerts.length === 0 && (
        <Card>
          <CardContent className="p-8 text-center">
            <i className="fas fa-check-circle text-4xl text-green-500 mb-4"></i>
            <h3 className="text-lg font-semibold text-slate-900 mb-2">¡Excelente cumplimiento!</h3>
            <p className="text-slate-600">
              No hay alertas pendientes. El sistema está funcionando correctamente 
              y cumple con todos los requisitos de la NOM-035-STPS-2018.
            </p>
          </CardContent>
        </Card>
      )}
    </div>
  );
}